### ISSUE TITLE
Can't do or receive calls

### ISSUE THREAD

**Issue by ArmeF97** [ArmeF97/oneplus6_lineageos_issues#5]
##### What is your...
* LineageOS version: lineage-16.0-20181114_155626
* LineageOS Download url: https://androidfilehost.com/?fid=11410963190603846662
* Gapps version: not installed.

 
##### Provide any additional information (observations/frequency of problem/last version it worked on/etc) as needed:
App "phone" crashes when I try to open it

**Comment by ArmeF97** [comment]
```
11-25 19:16:00.364  1162  3334 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
11-25 19:16:00.364  1162  3334 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
11-25 19:16:00.365  1162  3334 I OpenGLRenderer: Initialized EGL, version 1.4
11-25 19:16:00.365  1162  3334 D OpenGLRenderer: Swap behavior 2
11-25 19:16:00.649   880  1085 I ThermalEngine: Monitor : quiet_therm = 26972, msm_therm = 28532, xo_therm = 30098, battery_therm = 258,current_now = -246000
11-25 19:16:03.211  1162  1645 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher (has extras)} from uid 1000
11-25 19:16:03.223  1837  1837 V StatusBar: mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{6aa4301 V.ED..... ........ 0,0-1080,80} canPanelBeCollapsed(): false
11-25 19:16:03.225  1837  1837 I vol.Events: writeEvent dismiss_dialog volume_controller
11-25 19:16:03.277  2589  2722 W OpenGLRenderer: Incorrectly called buildLayer on View: Hotseat, destroying layer...
11-25 19:16:03.277  2589  2722 W OpenGLRenderer: Incorrectly called buildLayer on View: PageIndicatorLineCaret, destroying layer...
11-25 19:16:03.277  2589  2722 W OpenGLRenderer: Incorrectly called buildLayer on View: AllAppsRecyclerViewContainerView, destroying layer...
11-25 19:16:04.744  1162  4056 W system_server: Insufficient pre-allocated space to mmap vdex.
11-25 19:16:05.394  1162  4056 I chatty  : uid=1000 system_server identical 17 lines
11-25 19:16:05.449  1162  4056 W system_server: Insufficient pre-allocated space to mmap vdex.
11-25 19:16:05.458  1162  4056 I BackgroundDexOptService: Pinning optimized code {}
11-25 19:16:09.391  1162  1173 D WificondControl: Scan result ready event
11-25 19:16:09.393   985  1808 I LOWI-8.6.0.26: [LOWI-Scan] lowi_close_record:Scan done in 62968ms, 4 APs in scan results
11-25 19:16:12.316  2703  2703 W Notification: Use of stream types is deprecated for operations other than volume control
11-25 19:16:12.317  2703  2703 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-25 19:16:12.325  2703  2703 W Notification: Use of stream types is deprecated for operations other than volume control
11-25 19:16:12.325  2703  2703 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-25 19:16:12.468  1162  1201 E LightsService: Light requested not available on this device. 2
11-25 19:16:13.799   724   818 E CHRE    : Couldn't connect client socket to 'chre': Connection refused
11-25 19:16:13.800   724   818 W CHRE    : Failed to (re)connect, next try in 32000 ms
11-25 19:16:16.813  1162  1645 E LightsService: Light requested not available on this device. 2
11-25 19:16:16.896  1162  1173 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.android.dialer cmp=com.android.dialer/.app.DialtactsActivity bnds=[15,1995][225,2173] (has extras)} from uid 10007
11-25 19:16:16.923  3941  3941 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6249dbe
11-25 19:16:16.930  1162  1173 W ActivityManager: Request to remove task ignored for non-existent task 9
11-25 19:16:16.962  3941  3941 I Dialer  : DialtactsActivity.onCreate - enter
11-25 19:16:16.967  3941  3941 I Dialer  : DialtactsActivity.onAttachFragment - fragment: ReportFragment{6a01c58 #0 android.arch.lifecycle.LifecycleDispatcher.report_fragment_tag}
11-25 19:16:17.020  3941  3941 I Dialer  : DialtactsActivity.onAttachFragment - fragment: ListsFragment{399cab5 #1 id=0x7f09010a favorites}
11-25 19:16:17.020  3941  3941 I Dialer  : ListsFragment.onCreateView - enter
11-25 19:16:17.033  3941  3941 D AndroidRuntime: Shutting down VM
11-25 19:16:17.033  3941  3941 E AndroidRuntime: FATAL EXCEPTION: main
11-25 19:16:17.033  3941  3941 E AndroidRuntime: Process: com.android.dialer, PID: 3941
11-25 19:16:17.033  3941  3941 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.dialer/com.android.dialer.app.DialtactsActivity}: java.lang.SecurityException: Failed to find provider com.android.voicemail for user 0; expected to find a valid ContentProvider for this authority
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6680)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-25 19:16:17.033  3941  3941 E AndroidRuntime: Caused by: java.lang.SecurityException: Failed to find provider com.android.voicemail for user 0; expected to find a valid ContentProvider for this authority
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1950)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1918)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1868)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1972)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at com.android.dialer.app.list.ListsFragment.onCreateView(ListsFragment.java:227)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.Fragment.performCreateView(Fragment.java:2522)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7151)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7135)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        ... 11 more
11-25 19:16:17.033  3941  3941 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.content.IContentService$Stub.onTransact(IContentService.java:76)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at com.android.server.content.ContentService.onTransact(ContentService.java:262)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:731)
11-25 19:16:17.033  3941  3941 E AndroidRuntime:
11-25 19:16:17.035  1162  2564 W ActivityManager:   Force finishing activity com.android.dialer/.app.DialtactsActivity
11-25 19:16:17.039  1162  1192 I ActivityManager: Showing crash dialog for package com.android.dialer u0
11-25 19:16:17.101   775  1159 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=6909f27 Application Error: com.android.dialer)/@0x998d37d - animation-leash#0
11-25 19:16:17.101   775  1159 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=Dim Layer for - mAboveAppWindowsContainers)/@0x1de06c3 - animation-leash#0
11-25 19:16:17.101   775  1159 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=6909f27 Application Error: com.android.dialer)/@0x998d37d - animation-leash#0
11-25 19:16:17.101   775  1159 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=Dim Layer for - mAboveAppWindowsContainers)/@0x1de06c3 - animation-leash#0
11-25 19:16:17.538  1162  1191 W ActivityManager: Activity pause timeout for ActivityRecord{84b6d98 u0 com.android.dialer/.app.DialtactsActivity t10 f}
11-25 19:16:17.559   775  1159 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.android.dialer#0
11-25 19:16:17.559   775  1159 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.android.dialer#0
11-25 19:16:17.561  1162  1257 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5525 com.android.server.wm.WindowManagerService.removeWindow:1641 com.android.server.wm.Session.remove:226
11-25 19:16:17.802  1806  1806 E wpa_supplicant: wpa_driver_oem_initialize: NULL oem_handle , err: dlopen failed: library "/vendor/lib64/libwpa_drv_oem.so" not found
11-25 19:16:17.803  1806  1806 E wpa_supplicant: wpa_driver_oem_initialize: NULL oem_handle , err: dlopen failed: library "/vendor/lib64/libwpa_drv_oem.so" not found
11-25 19:16:17.825  1162  1820 D DhcpClient: Unicasting DHCPREQUEST ciaddr=192.168.1.104 request=0.0.0.0 serverid=null to /192.168.1.2:67
11-25 19:16:17.841  1162  2737 D DhcpClient: Received packet: 64:a2:f9:51:a1:f4 ACK: your new IP /192.168.1.104, netmask /255.255.255.0, gateways [/192.168.1.1] DNS servers: /8.8.8.8 /8.8.8.4 , lease time 60
11-25 19:16:17.841  1162  1820 D DhcpClient: Renewed lease: IP address 192.168.1.104/24 Gateway 192.168.1.1  DNS servers: [ 8.8.8.8 8.8.8.4 ] Domains  DHCP server /192.168.1.2 Vendor info null lease 60 seconds
11-25 19:16:17.844  1162  1820 D DhcpClient: Scheduling renewal in 29s
11-25 19:16:17.844  1162  1820 D DhcpClient: Scheduling rebind in 52s
11-25 19:16:17.844  1162  1820 D DhcpClient: Scheduling expiry in 59s
11-25 19:16:17.847  1806  1806 E wpa_supplicant: wpa_driver_oem_initialize: NULL oem_handle , err: dlopen failed: library "/vendor/lib64/libwpa_drv_oem.so" not found
11-25 19:16:18.087  2589  2722 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-25 19:16:20.148  1162  2564 W ActivityManager:   Force finishing activity com.android.dialer/.app.DialtactsActivity
11-25 19:16:20.166  1162  2564 I ActivityManager: Killing 3941:com.android.dialer/u0a20 (adj 900): crash
11-25 19:16:20.168  1162  1194 W libprocessgroup: kill(-3941, 9) failed: No such process
11-25 19:16:20.168   775   867 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
11-25 19:16:20.168   775   867 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
11-25 19:16:20.172   775   870 W SurfaceFlinger: Attempting to destroy on removed layer: 6909f27 Application Error: com.android.dialer#0
11-25 19:16:20.200   654   654 I Zygote  : Process 3941 exited due to signal (9)
11-25 19:16:20.211  1162  1194 W libprocessgroup: kill(-3941, 9) failed: No such process
11-25 19:16:20.211  1162  1194 I libprocessgroup: Successfully killed process cgroup uid 10020 pid 3941 in 44ms
PS C:\WINDOWS\system32>
```

**Comment by ArmeF97** [comment]
It seems that after deactivating com.android.contacts and deleting cache of related apps (and system apps), I can receive calls and make them
So, the issue has changed, need to open a new dedicated issue

**Comment by ArmeF97** [comment]
I was about to open a new issue, but it seems that now com.android.contacts works (I don't know why), so I simply reactivated

**Comment by aqxuwenda** [comment]
I think the real reason for this problem is due to Insufficient pre-allocated space to mmap vdex.
Because the vdex packet size is larger than the mmap (terminating address - starting address) size.
